import type { Metadata } from 'next';
import { Geist, Geist_Mono, Syne } from 'next/font/google';
import './globals.css';
import LayoutWrapper from '@/components/client/common/LayoutWrapper';
import { ReduxProvider } from '@/components/providers/ReduxProvider';
import { AuthProvider } from '@/context/AuthContext';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const syne = Syne({
    variable: '--font-syne',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${syne.variable} antialiased`}
                suppressHydrationWarning={true}
            >
                <ReduxProvider>
                    <AuthProvider>
                        <LayoutWrapper>{children}</LayoutWrapper>
                    </AuthProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
